// Background Service Worker for Shopper Copilot

console.log('Shopper Copilot: Background service worker started');

// Extension installation handler
chrome.runtime.onInstalled.addListener((details) => {
  console.log('Shopper Copilot: Extension installed', details);

  if (details.reason === 'install') {
    // First time installation
    chrome.storage.local.set({
      integrations: {
        whatsapp: false,
        telegram: false,
        messenger: false
      },
      settings: {
        autoSummarize: false,
        notificationsEnabled: true,
        theme: 'light'
      },
      friends: []
    });

    // Open welcome page (optional)
    console.log('Shopper Copilot: First time setup complete');
  }
});

// Handle messages from content scripts and popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log('Background received message:', request);

  switch (request.action) {
    case 'analyzePage':
      analyzePage(request.data)
        .then(result => sendResponse({ success: true, data: result }))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true; // Keep channel open for async response

    case 'sendToMessenger':
      sendToMessagingApp(request.platform, request.message, request.recipient)
        .then(result => sendResponse({ success: true, data: result }))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true;

    case 'getIntegrationStatus':
      chrome.storage.local.get(['integrations'], (result) => {
        sendResponse({ success: true, data: result.integrations || {} });
      });
      return true;

    case 'updateIntegration':
      updateIntegration(request.platform, request.status)
        .then(result => sendResponse({ success: true, data: result }))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true;

    default:
      sendResponse({ success: false, error: 'Unknown action' });
  }
});

// Page analysis function (placeholder for LLM integration)
async function analyzePage(pageData) {
  console.log('Analyzing page:', pageData);

  // In production, this would call an LLM API (OpenAI, Anthropic, etc.)
  // For now, return mock data
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        title: pageData.title,
        summary: 'This is a mock summary of the page. In production, this would be generated by an LLM based on the page content.',
        keyPoints: [
          'Key insight 1 from the page',
          'Important finding 2',
          'Notable point 3'
        ],
        links: pageData.links || [],
        sentiment: 'neutral',
        category: 'general'
      });
    }, 1000);
  });
}

// Send message to messaging apps
async function sendToMessagingApp(platform, message, recipient) {
  console.log(`Sending to ${platform}:`, message, recipient);

  // Get integration credentials from storage
  const integrations = await chrome.storage.local.get(['integrations']);

  if (!integrations.integrations || !integrations.integrations[platform]) {
    throw new Error(`${platform} is not connected. Please configure integration first.`);
  }

  // In production, this would call the respective messaging API
  // WhatsApp Business API: https://developers.facebook.com/docs/whatsapp
  // Telegram Bot API: https://core.telegram.org/bots/api
  // Messenger API: https://developers.facebook.com/docs/messenger-platform

  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        messageId: 'mock_' + Date.now(),
        platform: platform,
        sent: true,
        timestamp: new Date().toISOString()
      });
    }, 500);
  });
}

// Update integration status
async function updateIntegration(platform, status) {
  return new Promise((resolve, reject) => {
    chrome.storage.local.get(['integrations'], (result) => {
      const integrations = result.integrations || {};
      integrations[platform] = status;

      chrome.storage.local.set({ integrations }, () => {
        if (chrome.runtime.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
        } else {
          resolve({ platform, status });
        }
      });
    });
  });
}

// Context menu setup (optional - for right-click actions)
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: 'summarizePage',
    title: 'Summarize this page',
    contexts: ['page']
  });

  chrome.contextMenus.create({
    id: 'shareWithFriend',
    title: 'Share with friend',
    contexts: ['page', 'selection']
  });
});

// Handle context menu clicks
chrome.contextMenus.onClicked.addListener((info, tab) => {
  console.log('Context menu clicked:', info.menuItemId);

  switch (info.menuItemId) {
    case 'summarizePage':
      chrome.tabs.sendMessage(tab.id, {
        action: 'summarizePage'
      });
      break;

    case 'shareWithFriend':
      chrome.tabs.sendMessage(tab.id, {
        action: 'toggleWidget',
        tab: 'friends'
      });
      break;
  }
});

// Listen for tab updates (optional - for auto-summarization)
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status === 'complete' && tab.url) {
    console.log('Tab updated:', tab.url);

    // Check if auto-summarize is enabled
    chrome.storage.local.get(['settings'], (result) => {
      if (result.settings && result.settings.autoSummarize) {
        // Trigger auto-summarization
        chrome.tabs.sendMessage(tabId, {
          action: 'autoSummarize'
        });
      }
    });
  }
});

// Keep service worker alive (for long-running tasks)
setInterval(() => {
  console.log('Shopper Copilot: Service worker heartbeat');
}, 20000);

console.log('Shopper Copilot: Background service worker initialized');
